server:
  port: 8085

spring:
  application:
    name: dubbo-tech-openfeign-admin
  cloud:
    openfeign:
      httpclient:
        enabled: false
      okhttp:
        enabled: true
    loadbalancer:
      nacos:
        enabled: true